--COUNT UTILIZO EM CIMA DE VALORES AGREGADOS
SELECT EMBALAGEM, NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM;

--QUERO SABER QTOS PRODUTOS EU TENHO DE GARRAFA, LATA E PET
SELECT COUNT(EMBALAGEM), EMBALAGEM FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM ORDER BY EMBALAGEM;
SELECT COUNT(*), EMBALAGEM FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

-- PARA SABER QUANTOS PRODUTOS TEM DE CADA EMBALAGEM APENAS PARAO SABOR LARANJA
SELECT EMBALAGEM, COUNT(*) FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

SELECT EMBALAGEM, COUNT(*) AS NUMERO_DE_PRODUTOS FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Laranja' GROUP BY EMBALAGEM ORDER BY EMBALAGEM;

--QUANTAS VENDAS FORAM FEITAS COM A QUANTIDADE DE 99 LITROS PARA O PRODUTO 1101035?
SELECT QUANTIDADE, COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99 GROUP BY QUANTIDADE;

SELECT CODIGO_DO_PRODUTO, QUANTIDADE FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;

SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;