--DISTINCT
-- SELECT DISTINCT <Lista de campos> ou * FROM <Nome da Tabela> WHERE
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;

-- AO USAR O DISTINCT DESTA FORMA, ELE NÃO REPETE O CONJUNTO (EMBALAGEM + SABOR)
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;
SELECT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'Garrafa' AND SABOR = 'Uva';

SELECT DISTINCT EMBALAGEM,
                SABOR
FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';

SELECT EMBALAGEM,
       SABOR
FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';
