--ÚLTIMO SELECT DA AULA
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015';



--Apresentar só as VENDAS INVÁLIDAS e calculte a diferença entre o limite de venda máximo e o realizado, em percentuais
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015' AND TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA;


--Mostrando a diferença em valores 
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (TV.QUANTIDADE_TOTAL - TC.VOLUME_DE_COMPRA) AS DIFERENCA,    
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015' AND TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA;




--Mostrando a diferença em porcentagem 
--TV.QUANTIDADE_TOTAL é os 100%. 
--Qual porcentagem da quantidade total de vendas excedeu o volume limite de vendas
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    ROUND((((TV.QUANTIDADE_TOTAL - TC.VOLUME_DE_COMPRA)* 100) /TV.QUANTIDADE_TOTAL), 2)  AS DIFERENCA_PORCENTAGEM,    
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015' AND TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA;





--Resposta ALURA
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100,2)
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')) TV
ON TV.CPF = TC.CPF
WHERE TV.MES_ANO = '02-2015'
AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0;