--Exercicio - Listando somente clientes que tiveram vendas inválidas
--Calcular volume vendido por mês de cada cliente
SELECT TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
       TC.CPF,
       TC.NOME,
       TC.VOLUME_DE_COMPRA AS VOLUME_LIMITE,
       SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO,
       (CASE WHEN TC.VOLUME_DE_COMPRA >= SUM(INF.QUANTIDADE) THEN 'VENDAS VÁLIDAS'
       ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA,'MM-YYYY') = '02-2015'
GROUP BY TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')
HAVING TC.VOLUME_DE_COMPRA < SUM(INF.QUANTIDADE)
ORDER BY TO_CHAR(NF.DATA_VENDA,'MM-YYYY'), TC.NOME;





--Exercicio - CALCULANDO A DIFERENÇA ENTRE O LIMITE DE VENDA MÁXIMO E O REALIZADO EM PERCENTUAIS
--Listando somente clientes que tiveram vendas inválidas
--Calcular volume vendido por mês de cada cliente
/* DIFERENÇA EM PORCENTAGEM
VOLUME_LIMITE      100%
DIFERENCA           X
X = (DIFERENCA * 100) / VOLUME_LIMITE
*/
SELECT TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
       TC.CPF,
       TC.NOME,
       TC.VOLUME_DE_COMPRA AS VOLUME_LIMITE,
       SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO,
       ROUND( ( (TC.VOLUME_DE_COMPRA - SUM(INF.QUANTIDADE)) * 100) / TC.VOLUME_DE_COMPRA, 2 )  || '%' AS DIFERENCA,
       (CASE WHEN TC.VOLUME_DE_COMPRA >= SUM(INF.QUANTIDADE) THEN 'VENDAS VÁLIDAS'
       ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA,'MM-YYYY') = '02-2015'
GROUP BY TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')
HAVING TC.VOLUME_DE_COMPRA < SUM(INF.QUANTIDADE)
ORDER BY TO_CHAR(NF.DATA_VENDA,'MM-YYYY'), TC.NOME;
--OBS: O meu foi mais rápido do que o da Alura



--DA ALURA
SELECT
TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TV.MES_ANO, TV.QUANTIDADE_TOTAL,
(CASE WHEN TC.VOLUME_DE_COMPRA >= TV.QUANTIDADE_TOTAL THEN 'VENDAS VÁLIDAS'
ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO,
ROUND((1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100,2)
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(SELECT
NF.CPF,
TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,
SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
GROUP BY
CPF, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')) TV
ON TV.CPF = TC.CPF
WHERE TV.MES_ANO = '02-2015'
AND (TC.VOLUME_DE_COMPRA - TV.QUANTIDADE_TOTAL) < 0



