--Esta consulta traz o número de dias que uma pessoa viveu desde o seu nascimento:

SELECT NOME, DATA_DE_NASCIMENTO, (SYSDATE - DATA_DE_NASCIMENTO) FROM TABELA_DE_CLIENTES;

--E também retorna um número decimal, porque SYSDATE é expresso em horas/minutos/segundos
--e a parte decimal representa as horas desde a última meia noite.

SELECT 12400/365 FROM DUAL; --33,87

--Arredondando para o número de dias vividos pela pessoa:
SELECT NOME, DATA_DE_NASCIMENTO, TRUNC(SYSDATE - DATA_DE_NASCIMENTO) FROM TABELA_DE_CLIENTES;

--=============================================================================================
--Na tabela de notas fiscais, temos o valor do imposto. 
--Já na tabela de itens, temos a quantidade e o faturamento. 
--Calcule o valor do imposto pago no ano de 2016, arredondando para o menor inteiro.

SELECT SYSDATE, TO_CHAR(SYSDATE, 'YYYY') FROM DUAL;


--RESPOSTA DA ALURA:
SELECT TO_CHAR(DATA_VENDA, 'YYYY'), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');


----MINHA TENTATIVA DE ACERTAR----------
SELECT TO_CHAR(DATA_VENDA, 'YYYY'), 
       FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO)))
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY')
HAVING TO_CHAR(DATA_VENDA, 'YYYY') = '2016';


------------------------------VENDO SE ESTÁ CERTO-----------------------------
SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 5;

SELECT COUNT(*) FROM NOTAS_FISCAIS;
SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS;

SELECT * FROM NOTAS_FISCAIS WHERE ROWNUM <= 5 AND TO_CHAR(DATA_VENDA, 'YYYY') = '2016' ORDER BY NUMERO; --NUMERO: 27192, 27193, 27194, 27195,27196
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO = 27192; --CODIGO_DO_PRODUTO: 1022450, 1037797, 1086543, 783663
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO = 27193; --CODIGO_DO_PRODUTO: 773912
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO = 27194; --CODIGO_DO_PRODUTO: 1000889
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO = 27195; --CODIGO_DO_PRODUTO: 1004327, 1041119, 1078680
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO = 27196; --CODIGO_DO_PRODUTO: 520380

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE NUMERO IN (27192, 27193, 27194, 27195,27196);

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN ('1022450','1037797', '1086543', '783663');
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN ('773912');
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN ('1000889');
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN ('1004327', '1041119', '1078680');
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN ('520380');

SELECT TO_CHAR(DATA_VENDA, 'YYYY'),
       FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO)))
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016' AND NF.NUMERO IN (27192, 27193, 27194, 27195,27196)
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');


--O ROWNUM ESTÁ PEGANDO POR ITENS DE CADA NOTA FISCAL. 
--NO MEU EXEMPLO TEM 10 ITENS (CONTANDO COM TODOS OS ITENS DAS 5 NOTAS FISCAIS). 
--QUANDO COLOCO ROWNUM=10, FUNCIONA!
SELECT TO_CHAR(DATA_VENDA, 'YYYY'),
       SUM(IMPOSTO * (QUANTIDADE * PRECO))
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE ROWNUM <= 10 AND TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');

--SE COLOCO ROWNUM=5, ELE PEGA OS 4 ITENS DA NOTA FISCAL NUMERO 27192 + 1 ITEM DA NOTA FISCAL 27193 
--E NÃO PEGA AS OUTRAS 4 NOTAS FISCAIS. 
--EU QUERIA 5 NOTAS FISCAIS E NÃO 5 ITENS.
SELECT TO_CHAR(DATA_VENDA, 'YYYY'),
        IMPOSTO, 
        QUANTIDADE,
        PRECO,
       SUM(IMPOSTO * (QUANTIDADE * PRECO))
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE ROWNUM <= 5 AND TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
GROUP BY TO_CHAR(DATA_VENDA, 'YYYY'),IMPOSTO, QUANTIDADE, PRECO;
