/* Verifique as quantidades totais de vendas de cada produto 1101035 
e ordene da maior para a menor.
Use a tabela de itens das notas fiscais
*/

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY NUMERO;


-- AGRUPADO PELO CÓDIGO DO PRODUTO (PARA VER OS MAIS VENDIDOS)
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;


-- Agora, liste somente os produtos que venderam mais que 394000 unidades.
SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 ORDER BY SUM(QUANTIDADE) DESC;
