-- A consulta abaixo dá os produtos cuja soma das vendas são maiores que 394000:

SELECT SUM(INF.QUANTIDADE),
       TP.NOME_DO_PRODUTO
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
GROUP BY TP.NOME_DO_PRODUTO
HAVING SUM(INF.QUANTIDADE) > 394000;



SELECT INF.CODIGO_DO_PRODUTO FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;




-- USANDO DUAS CONSULTAS
SELECT CODIGO_DO_PRODUTO, 
       SUM(QUANTIDADE) 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO 
HAVING SUM(QUANTIDADE) > 394000
ORDER BY SUM(QUANTIDADE) DESC;

SELECT NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO IN ('479745', '229900', '326779', '235653', '1040107');

-- Listando os nomes dos produtos selecionados
SELECT NOME_DO_PRODUTO 
FROM TABELA_DE_PRODUTOS 
WHERE CODIGO_DO_PRODUTO IN (
            SELECT CODIGO_DO_PRODUTO
            FROM ITENS_NOTAS_FISCAIS 
            GROUP BY CODIGO_DO_PRODUTO 
            HAVING SUM(QUANTIDADE) > 394000);
            

-- Listando os sabores dos produtos que são selecionados
-- Está certo, porque deu o mesmo resultado da resposta da Alura
SELECT DISTINCT SABOR 
FROM TABELA_DE_PRODUTOS 
WHERE CODIGO_DO_PRODUTO IN (
            SELECT CODIGO_DO_PRODUTO
            FROM ITENS_NOTAS_FISCAIS 
            GROUP BY CODIGO_DO_PRODUTO 
            HAVING SUM(QUANTIDADE) > 394000)
ORDER BY SABOR;

-- Codigo da Alura onde inclui o campo de sabor do produto
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, TP.SABOR, SUM(INF.QUANTIDADE) 
FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, TP.SABOR HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS;

-- Resposta da Alura 
SELECT DISTINCT SABOR 
FROM TABELA_DE_PRODUTOS 
WHERE CODIGO_DO_PRODUTO IN (
        SELECT INF.CODIGO_DO_PRODUTO 
        FROM ITENS_NOTAS_FISCAIS INF
        INNER JOIN TABELA_DE_PRODUTOS TP 
        ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
        GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, TP.SABOR HAVING SUM(INF.QUANTIDADE) > 394000);