--FUNCOES DE STRING

-- LOWER(), UPPER()
SELECT NOME FROM TABELA_DE_CLIENTES;
SELECT NOME, LOWER(NOME) FROM TABELA_DE_CLIENTES;
SELECT NOME, LOWER(NOME), UPPER(NOME) FROM TABELA_DE_CLIENTES;

--INITCAP()
SELECT NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

--CONCAT()
SELECT ENDERECO_1, BAIRRO FROM TABELA_DE_CLIENTES;
SELECT ENDERECO_1, BAIRRO,  CONCAT(ENDERECO_1, BAIRRO) FROM TABELA_DE_CLIENTES;
SELECT ENDERECO_1, BAIRRO, CONCAT(CONCAT(ENDERECO_1, ' '), BAIRRO) FROM TABELA_DE_CLIENTES;

--CONCATENAR COM PIPE ||
SELECT ENDERECO_1 || ' ' || BAIRRO || ' ' || CIDADE || ' ' || ESTADO || ' ' ||  CEP FROM TABELA_DE_CLIENTES;

--LPAD(campo, quantidadeTotalCaracteres, preencherComQue) - LEFT PAD - preenche à esquerda
--RPAD(campo, quantidadeTotalCaracteres, preencherComQue) - RIGHT PAD - preenche à direita
SELECT NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 70, '*') FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO, 70, '*') FROM TABELA_DE_PRODUTOS;

--SUBSTR(campo, ondeComeca, qtosCaracteresPega)
SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO, 3, 5) FROM TABELA_DE_PRODUTOS;

--INSTR(campoDaTabela, palavraParaProcurar) -> Se retornar 0, não achou. Se retornar um número é onde a palavra procurada começa.
SELECT NOME_DO_PRODUTO, INSTR(NOME_DO_PRODUTO, 'Campo') FROM TABELA_DE_PRODUTOS;

SELECT NOME FROM TABELA_DE_CLIENTES;
SELECT NOME, INSTR(NOME, 'Mattos') FROM TABELA_DE_CLIENTES;

--INSTR no WHERE. Mostra só <> 0, que significa os registros que têm a palavra procurada
SELECT NOME FROM TABELA_DE_CLIENTES WHERE  INSTR(NOME, 'Mattos') <> 0;

--LTRIM(), RTRIM(), TRIM()
--DUAL é uma tabela que não existe.
SELECT '   PATRICIA    ' FROM DUAL;
SELECT '   PATRICIA    ', LTRIM('   PATRICIA    ') FROM DUAL;
SELECT '   PATRICIA    ', LTRIM('   PATRICIA    ') AS L, RTRIM('   PATRICIA    ') AS R FROM DUAL;
SELECT '   PATRICIA    ', LTRIM('   PATRICIA    ') AS L, RTRIM('   PATRICIA    ') AS R, TRIM('   PATRICIA    ') AS LR FROM DUAL;

--REPLACE()
SELECT NOME_DO_PRODUTO FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, REPLACE(NOME_DO_PRODUTO, 'Litro', 'L') FROM TABELA_DE_PRODUTOS;
SELECT NOME_DO_PRODUTO, REPLACE(REPLACE(NOME_DO_PRODUTO, 'Litro', 'L'), 'Ls', 'L') FROM TABELA_DE_PRODUTOS;