/* SELECT DISTINCT 
   <Lista de campos> ou * 
   FROM <Nome da Tabela> 
   WHERE <Filtro> 
   AND ROWNUM <= <VALOR> 
   GROUP BY <CAMPOS> 
   ORDER BY <CAMPOS> (ASC,DESC)
*/

/* QUANDO UTILIZAR O 'GROUP BY', NA LISTA DE CAMPOS NUMÉRICOS QUE VOCÊ ESTÁ ESCOLHENDO PARA AGRUPAR,
   COLOCAR A FÓRMULA MATEMÁTICA QUE VAI DIZER SE VOU SOMAR, CALCULAR A MÉDIA, ETC.:(SUM, AVG, MIN, MAX, COUNT)
*/

-- VOCÊ SÓ PÕE NO 'GROUP BY' OS CAMPOS NÃO NUMÉRICOS
-- E PARA FAZER A 'SUM, AVG, MIN, MAX' VOCÊ SÓ PÕE CAMPOS NUMÉRICOS

SELECT * FROM TABELA_DE_CLIENTES;

SELECT ESTADO, 
       SUM(VOLUME_DE_COMPRA) SOMA
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

SELECT ESTADO, 
       MIN(VOLUME_DE_COMPRA) MINIMO
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

SELECT ESTADO, 
       MAX(VOLUME_DE_COMPRA) MAXIMO
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

SELECT ESTADO, 
       AVG(VOLUME_DE_COMPRA) MEDIA
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;

SELECT ESTADO, 
       ROUND(AVG(VOLUME_DE_COMPRA), 2) MEDIA
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO;
--------------------------------------------------------------------------------

SELECT * FROM TABELA_DE_CLIENTES;

SELECT CIDADE,
       SUM (IDADE)     
FROM TABELA_DE_CLIENTES
GROUP BY CIDADE;

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;
SELECT DISTINCT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE;

/* OS CAMPOS QUE NÃO ESTAO NO CRITÉRIO DE AGREGAÇÃO, OU SEJA, NO 'GROUP BY', DEVEM SER NUMÉRICOS, 
 QUE NESTE CASO É A 'IDADE', ENTÃO APLICA-SE 'a formula' DE AGREGAÇÃO NELE (SUM, AVG, MIN, MAX, COUNT)
 E NO ORDER BY, NÃO SE COLOCA O CAMPO NUMÉRICO QUE ESTÁ SENDO USADO PARA FAZER A AGREGAÇÃO (NESTE CASO 'IDADE')
*/
SELECT CIDADE, SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;
SELECT CIDADE, AVG(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;
SELECT CIDADE, ROUND(AVG(IDADE),2) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE;

SELECT CIDADE, SUM(LIMITE_DE_CREDITO), SUM(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE;

-- QUAL É O PRODUTO MAIS CARO DE CADA EMBALAGEM?
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;