--HAVING É UM FILTRO SOBRE O RESULTADO DA AGREGAÇÃO
--

/* SELECT DISTINCT <Lista de campos> ou *
   FROM <Nome da tabela>
   WHERE <Filtro> AND ROWNUM <= <VALOR>
   GROUP BY <CAMPOS>
   ORDER BY <CAMPOS> (ASC, DESC)
   HAVING <CONDICAO>
*/

-- Ex.: SELECT ESTADO, SUM(NUM_FUNC) FROM CLIENTE 
--      WHERE SUM(NUM_FUNC) >= 60 GROUP BY ESTADO
-- ESTA CONSULTA NÃO FUNCIONA!

--O 'SUM' NOS ATRIBUTOS É APLICADO NO RESULTADO DA CONSULTA
-- O FILTRO WHERE É APLICADO SOBRE A TABELA

SELECT * FROM TABELA_DE_CLIENTES;

-- OLHAR POR ESTADO O LIMITE DE CRÉDITO
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES GROUP BY ESTADO;
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) FROM TABELA_DE_CLIENTES GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) >= 900000;

SELECT * FROM TABELA_DE_PRODUTOS;
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM HAVING MAX(PRECO_DE_LISTA) >= 10;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM TABELA_DE_PRODUTOS 
GROUP BY EMBALAGEM HAVING MAX(PRECO_DE_LISTA) >= 10 AND MIN(PRECO_DE_LISTA) <= 10;



--USANDO UM CRITÉRIO QUE NÃO É SOBRE A AGREGAÇÃO (PRECO_DE_LISTA), POSSO USAR O 'WHERE'
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM TABELA_DE_PRODUTOS WHERE PRECO_DE_LISTA >= 10 GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM TABELA_DE_PRODUTOS 
WHERE PRECO_DE_LISTA >= 10 
GROUP BY EMBALAGEM  HAVING MAX(PRECO_DE_LISTA) >= 20;