/*  INNER JOIN

SELECT C.CLIENTE, 
       C.ESTADO, 
       M.DATA, 
       M.VALOR_VENDA
FROM CLIENTE C 
INNER JOIN MOVIMENTO M
ON C.CLIENTE = M.CLIENTE;
*/

SELECT * FROM TABELA_DE_VENDEDORES;
SELECT * FROM NOTAS_FISCAIS;
SELECT COUNT(*) FROM NOTAS_FISCAIS;
SELECT COUNT(*) FROM NOTAS_FISCAIS GROUP BY CPF;

SELECT MATRICULA, COUNT(*) AS NUMERO_DE_NOTAS 
FROM NOTAS_FISCAIS GROUP BY MATRICULA;

--QUANTIDADE DE REGISTROS(NOTAS FISCAIS) POR CPF
SELECT COUNT(*), NF.CPF, TV.NOME 
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_VENDEDORES TV
ON NF.MATRICULA = TV.MATRICULA
GROUP BY NF.CPF, TV.NOME
ORDER BY TV.NOME, NF.CPF;

--QTDE DE REGISTROS(NOTAS FISCAIS) POR NOME
SELECT COUNT(*), TV.NOME 
FROM NOTAS_FISCAIS NF
INNER JOIN TABELA_DE_VENDEDORES TV
ON NF.MATRICULA = TV.MATRICULA
GROUP BY TV.NOME
ORDER BY TV.NOME;

--QUANTAS NOTAS FISCAIS CADA VENDEDOR VENDEU:
SELECT NF.MATRICULA,
       TV.NOME,
       COUNT(*) AS NUMERO_DE_NOTAS
FROM TABELA_DE_VENDEDORES TV
INNER JOIN NOTAS_FISCAIS NF
ON TV.MATRICULA = NF.MATRICULA
GROUP BY NF.MATRICULA, TV.NOME
ORDER BY NUMERO_DE_NOTAS DESC;
