-- SERVE PARA ORDENAR A SAIDA
-- SELECT * FROM <NOME DA TABELA> WHERE <FILTRO> AND ROWNUM <= <VALOR> ORDER BY <CAMPOS> (ASC, DESC)

SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;

SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;

--ORDENO AS MINHAS EMBALAGENS E DENTRO DE CADA UMA DELAS ORDERNAR PELO NOME DO PRODUTO
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO DESC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;


--UTILIZANDO 2 QUERIES SQL, QUAL FOI A MAIOR VENDA DO PRODUTO 'LINHA REFRESCANTE - 1 LITRO - MORANGO/LIMAO', EM QUANTIDADE?
SELECT * FROM TABELA_DE_PRODUTOS WHERE NOME_DO_PRODUTO = 'Linha Refrescante - 1 Litro - Morango/Limao';
--código do produto = 1101035
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;
