SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    ROUND((((TV.QUANTIDADE_TOTAL - TC.VOLUME_DE_COMPRA)* 100) /TV.QUANTIDADE_TOTAL), 2)  AS DIFERENCA_PORCENTAGEM,    
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015' AND TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA;



-- Ranking Vendas de Produtos por Sabor Descendente, dentro de um ano específico, e
-- Percentual de distribuição daquele sabor em relação às vendas totais
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    ROUND((((TV.QUANTIDADE_TOTAL - TC.VOLUME_DE_COMPRA)* 100) /TV.QUANTIDADE_TOTAL), 2)  AS DIFERENCA_PORCENTAGEM,    
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015' AND TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA;


--Total por sabor e por ano
SELECT 
    TP.SABOR,
    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL    
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
GROUP BY  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;

--Achar o total de venda dentro do ano (maneira 1)
SELECT 
        SUB.ANO,
        SUM(SUB.QUANTIDADE_TOTAL)
FROM 
(
SELECT 
    TP.SABOR,
    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL    
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
GROUP BY  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
) SUB
GROUP BY SUB.ANO;


--Achar o total de venda dentro do ano (maneira 2)
SELECT 
        EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) as TOTAL_GERAL
FROM 
ITENS_NOTAS_FISCAIS INF 
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA);


--Fazendo um SELECT na query acima para retornar somente 1 resultado, 
SELECT SUB.TOTAL_GERAL
FROM 
(SELECT 
        EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) as TOTAL_GERAL
FROM 
ITENS_NOTAS_FISCAIS INF 
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA)) SUB;


--pode-se colocar uma query que retorna 1 resultado como um campo de outra query
SELECT 
    TP.SABOR,
    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
    SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
    (SELECT SUB.TOTAL_GERAL
     FROM 
        (SELECT 
                EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
                SUM(INF.QUANTIDADE) as TOTAL_GERAL
        FROM 
        ITENS_NOTAS_FISCAIS INF 
        INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
        WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
        GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA)) SUB
    ) AS TOTAL_GERAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
GROUP BY  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC;


--QUANTIDADE_TOTAL é quanto em porcentagem do TOTAL_GERAL:
SELECT CONSULTA_RELATORIO.SABOR, 
       CONSULTA_RELATORIO.ANO,
       CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
       CONSULTA_RELATORIO.TOTAL_GERAL,
       ROUND(((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.TOTAL_GERAL) * 100),2) AS PERCENTUAL_PARTICIPACAO       
FROM        
    (SELECT 
        TP.SABOR,
        EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
        (SELECT SUB.TOTAL_GERAL
         FROM 
            (SELECT 
                    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
                    SUM(INF.QUANTIDADE) as TOTAL_GERAL
            FROM 
            ITENS_NOTAS_FISCAIS INF 
            INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
            WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
            GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA)) SUB
        ) AS TOTAL_GERAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
    WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
    GROUP BY  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
    ORDER BY SUM(INF.QUANTIDADE) DESC) CONSULTA_RELATORIO;
