--Query final do arquivo 'Ranking_vendas_produtos_por_sabor'
--QUANTIDADE_TOTAL é quanto em porcentagem do TOTAL_GERAL:
SELECT CONSULTA_RELATORIO.SABOR, 
       CONSULTA_RELATORIO.ANO,
       CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
       CONSULTA_RELATORIO.TOTAL_GERAL,
       ROUND(((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.TOTAL_GERAL) * 100),2) AS PERCENTUAL_PARTICIPACAO       
FROM        
    (SELECT 
        TP.SABOR,
        EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
        (SELECT SUB.TOTAL_GERAL
         FROM 
            (SELECT 
                    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
                    SUM(INF.QUANTIDADE) as TOTAL_GERAL
            FROM 
            ITENS_NOTAS_FISCAIS INF 
            INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
            WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
            GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA)) SUB
        ) AS TOTAL_GERAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
    WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
    GROUP BY  TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
    ORDER BY SUM(INF.QUANTIDADE) DESC) CONSULTA_RELATORIO;
    
    
--Modificando a query anterior para fazer o Ranking de vendas por tamanho
SELECT CONSULTA_RELATORIO.TAMANHO, 
       CONSULTA_RELATORIO.ANO,
       CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
       CONSULTA_RELATORIO.TOTAL_GERAL,
       ROUND(((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.TOTAL_GERAL) * 100),2) AS PERCENTUAL_PARTICIPACAO       
FROM        
    (SELECT 
        TP.TAMANHO,
        EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
        SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL,
        (SELECT SUB.TOTAL_GERAL
         FROM 
            (SELECT 
                    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
                    SUM(INF.QUANTIDADE) as TOTAL_GERAL
            FROM 
            ITENS_NOTAS_FISCAIS INF 
            INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
            WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
            GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA)) SUB
        ) AS TOTAL_GERAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
    WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
    GROUP BY  TP.TAMANHO, EXTRACT(YEAR FROM NF.DATA_VENDA)
    ORDER BY SUM(INF.QUANTIDADE) DESC) CONSULTA_RELATORIO;
    
    
--Resposta ALURA    
SELECT CONSULTA_RELATORIO.TAMANHO, 
CONSULTA_RELATORIO.ANO,
CONSULTA_RELATORIO.QUANTIDADE_TOTAL,
ROUND((CONSULTA_RELATORIO.QUANTIDADE_TOTAL/CONSULTA_RELATORIO.QUANTIDADE_GERAL)*100,2) AS 
PERCENTUAL_PARTICIPACAO
FROM
(SELECT
TP.TAMANHO,EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO ,SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
,(SELECT TOTAL_ANO.QUANTIDADE_GERAL FROM
(SELECT
EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
,SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
FROM
NOTAS_FISCAIS NF
INNER JOIN
ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY EXTRACT(YEAR FROM NF.DATA_VENDA)) TOTAL_ANO
) AS QUANTIDADE_GERAL
FROM TABELA_DE_PRODUTOS TP
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF
ON INF.NUMERO = NF.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO,EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC) CONSULTA_RELATORIO;

    
    
--AJUSTANDO IDENTAÇÃO DA QUERY (É A MESMA QUERY ANTERIOR)
SELECT CONSULTA_RELATORIO.TAMANHO
       ,CONSULTA_RELATORIO.ANO
       ,CONSULTA_RELATORIO.QUANTIDADE_TOTAL
       ,CONSULTA_RELATORIO.TOTAL_GERAL
       ,ROUND(((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.TOTAL_GERAL) * 100),2) AS PERCENTUAL_PARTICIPACAO       
FROM        
    (SELECT 
        TP.TAMANHO
        ,EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
        ,SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
        ,
            (SELECT SUB.TOTAL_GERAL FROM 
                (SELECT 
                    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
                    ,SUM(INF.QUANTIDADE) AS TOTAL_GERAL
                FROM 
                ITENS_NOTAS_FISCAIS INF INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
                WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
                GROUP BY  EXTRACT(YEAR FROM NF.DATA_VENDA)) SUB
            ) AS TOTAL_GERAL
    FROM TABELA_DE_PRODUTOS TP
    INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
    WHERE TO_CHAR(NF.DATA_VENDA, 'YYYY') = 2016
    GROUP BY  TP.TAMANHO, EXTRACT(YEAR FROM NF.DATA_VENDA)
    ORDER BY SUM(INF.QUANTIDADE) DESC) 
    CONSULTA_RELATORIO;    