-- POSSO LIMITAR E OLHAR AS PRIMEIRAS LINHAS DA MINHA SELEÇÃO
-- SELECT * FROM CLIENTE WHERE ROWNUM <= 4;

SELECT * FROM TABELA_DE_PRODUTOS;

SELECT ROWNUM, TABELA_DE_PRODUTOS.* FROM TABELA_DE_PRODUTOS;
SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP;

SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 5;
SELECT TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM <= 3;

-- NÃO FUNCIONA PARA PEGAR LINHAS NO "MEIO" DOS REGISTROS
-- RESOLVEREMOS ESTE PROBLEMA MAIS PRA FRENTE COM OUTROS CONHECIMENTOS DE SQL
SELECT ROWNUM, TP.* FROM TABELA_DE_PRODUTOS TP WHERE ROWNUM >= 2 AND ROWNUM <= 3;


--COMANDO SQL PARA LISTAR AS 10 PRIMEIRAS VENDAS DO DIA 01/10/2017
SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = '01/10/2017' AND ROWNUM <= 10;
SELECT * FROM NOTAS_FISCAIS WHERE DATA_VENDA = TO_DATE('01/10/2017', 'DD/MM/YYYY') AND ROWNUM <= 10;