SELECT * FROM TABELA_DE_CLIENTES;

SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '13/01/95';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO_DATE('13/01/1995', 'DD/MM/YYYY');

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO_DATE('01/13/1995', 'MM/DD/YYYY');


SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO BETWEEN TO_DATE('13/01/1995', 'DD/MM/YYYY') AND TO_DATE('14/11/1995', 'DD/MM/YYYY');

--ORDENA POR ORDEM ALFABETICA
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'Lapa';

SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND IDADE >= 20;
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND (IDADE >= 20 AND IDADE <= 25);
SELECT * FROM TABELA_DE_CLIENTES WHERE CIDADE IN ('Rio de Janeiro', 'Sao Paulo') AND (IDADE BETWEEN 20 AND 25);

SELECT * FROM TABELA_DE_CLIENTES WHERE NOME LIKE '%Silva%';
