-- SUBCONSULTA substituindo o HAVING
/*
SELECT ESTADO, SUM(NUM_FUNC) 
FROM CLIENTE 
GROUP BY ESTADO
HAVING SUM(NUM_FUNC) >= 60
*/

-- NÃO podemos fazer o FILTRO (WHERE) nas funções(sum, avg, min, max, count), então usamos o HAVING.

/*
SELECT ESTADO, SUM(NUM_FUNC) FROM CLIENTE GROUP BY ESTADO;
     Posso fazer um outro SELECT em cima do resultado da consulta acima
SELECT ESTADO, NUM_FUNC FROM ESTADO_FUNC WHERE NUM_FUNC >= 60;
*/

-- Então fica assim:
/*

SELECT ESTADO_FUNC.ESTADO, 
       ESTADO_FUNC.NUM_FUNC 
FROM 
    (
    SELECT ESTADO, SUM(NUM_FUNC) FROM CLIENTE GROUP BY ESTADO
    ) ESTADO_FUNC
    
WHERE ESTADO_FUNC.NUM_FUNC >= 60;

*/

-- Relembrando o HAVING
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) > 90;

-- Como faríamos isso, usando uma SUBQUERY?
SELECT SUBQUERY.EMBALAGEM, 
       SUBQUERY.SOMA_PRECO
FROM (
    SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
    FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
    ) SUBQUERY
WHERE SUBQUERY.SOMA_PRECO >= 80;

SELECT SOMA_EMBALAGENS.EMBALAGEM, 
       SOMA_EMBALAGENS.SOMA_PRECO
FROM (
    SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
    FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
    ) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;