--Quais clientes fizeram pelo menos uma compra:

SELECT DISTINCT NF.CPF,
        CLI.CPF,
        CLI.NOME
FROM TABELA_DE_CLIENTES CLI 
INNER JOIN NOTAS_FISCAIS NF
ON CLI.CPF = NF.CPF;

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

-- copia do insert antigo para comparar com o de baixo que estava dando erro
INSERT INTO TABELA_DE_CLIENTES (CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) VALUES ('1471156710', 'Erica Carvalho', 'R. Iriquitia', '', 'Jardins', 'Sao Paulo', 'SP', '80012212', TO_DATE('1990-09-01','YYYY-MM-DD'), 27, 'F', 170000.0000, 24500, 0);

-- DEU CERTO ESTE INSERT, FALTAVA O UNDERLINE NO ENDERECO_
INSERT INTO TABELA_DE_CLIENTES (CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', NULL, 'Bangu', 'Rio de Janeiro', 'RJ', '23400000', TO_DATE('1989-02-04', 'YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);

SELECT * FROM TABELA_DE_CLIENTES;

SELECT DISTINCT 
                --NF.CPF AS CPF_NOTA_FISCAL, 
                C.CPF AS CPF_CLIENTES, 
                C.NOME
FROM TABELA_DE_CLIENTES C LEFT JOIN NOTAS_FISCAIS NF
ON C.CPF = NF.CPF
WHERE NF.CPF IS NULL;

-- JOIN NO CAMPO TABELA_DE_CLIENTES.BAIRRO E TABELA_DE_VENDEDORES.BAIRRO (Usando campo BAIRRO como FK)
SELECT V.BAIRRO AS V_BAIRRO,
       V.NOME AS V_NOME,
       C.BAIRRO AS C_BAIRRO,
       C.NOME AS C_NOME
FROM TABELA_DE_VENDEDORES V INNER JOIN TABELA_DE_CLIENTES C
ON V.BAIRRO = C.BAIRRO;


-- ONDE TEM VENDEDOR QUE TEM ESCRITÓRIO, ONDE NÃO TEM CLIENTE
SELECT V.BAIRRO AS V_BAIRRO,
       V.NOME AS V_NOME,
       C.BAIRRO AS C_BAIRRO,
       C.NOME AS C_NOME
FROM TABELA_DE_VENDEDORES V LEFT JOIN TABELA_DE_CLIENTES C
ON V.BAIRRO = C.BAIRRO;

-- ONDE TEM CLIENTE, MAS NÃO TEM ESCRITORIO DO VENDEDOR
SELECT V.BAIRRO AS V_BAIRRO,
       V.NOME AS V_NOME,
       C.BAIRRO AS C_BAIRRO,
       C.NOME AS C_NOME
FROM TABELA_DE_VENDEDORES V RIGHT JOIN TABELA_DE_CLIENTES C
ON V.BAIRRO = C.BAIRRO;

-- QUERO VER OS 2 CASOS AO MESMO TEMPO: O QUE TEM NOS 2 E O QUE TEM SOMENTE EM UM DOS DOIS. LEFT JOIN + RIGHT JOIN = FULL JOIN.
SELECT DISTINCT
       V.BAIRRO AS V_BAIRRO,
       V.NOME AS V_NOME,
       C.BAIRRO AS C_BAIRRO,
       C.NOME AS C_NOME
FROM TABELA_DE_VENDEDORES V FULL JOIN TABELA_DE_CLIENTES C
ON V.BAIRRO = C.BAIRRO;