--VENDAS VALIDAS
--vendas dentro de um período especificado para saber se algum cliente ultrapassou o volume de compra

SELECT * FROM TABELA_DE_CLIENTES;
SELECT * FROM NOTAS_FISCAIS;

--Calculo do volume total de compras de cada cliente:
SELECT * FROM ITENS_NOTAS_FISCAIS;

--Aqui ficou separado por data
SELECT NF.CPF,
       NF.DATA_VENDA,
       INF.QUANTIDADE
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO;

-- Pode ter a mesma data, e ser para o mesmo cliente, mas são produtos diferentes
SELECT NF.CPF,
       TP.CODIGO_DO_PRODUTO,
       TP.NOME_DO_PRODUTO,
       NF.DATA_VENDA,
       INF.QUANTIDADE
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_PRODUTOS TP ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO;

--Juntando toda a quantidade vendida por cliente dentro de um mês
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
ORDER BY TO_CHAR(NF.DATA_VENDA, 'MM-YYYY');

--Montar uma query para comparar o VOLUME_DE_COMPRA com a QUANTIDADE_TOTAL
SELECT CPF, NOME, VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES;

--O prof usou o SELECT como tabela para fazer o INNER JOIN
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TV.CPF AS VENDAS_CPF,
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF;


-- Usando o CASE WHEN para comparar os campos
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF;


--Filtrando por 02-2015
SELECT
    TC.CPF AS CLIENTE_CPF, 
    TC.NOME AS CLIENTE_NOME,
    TV.MES_ANO AS VENDAS_MES_ANO,
    TC.VOLUME_DE_COMPRA,
    TV.QUANTIDADE_TOTAL,
    (CASE WHEN TV.QUANTIDADE_TOTAL > TC.VOLUME_DE_COMPRA THEN 'VENDAS INVÁLIDAS' ELSE 'VENDAS VÁLIDAS' END) AS RESULTADO
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
(
SELECT NF.CPF,
       TO_CHAR(NF.DATA_VENDA, 'MM-YYYY') AS MES_ANO,
       SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY NF.CPF, TO_CHAR(NF.DATA_VENDA, 'MM-YYYY')
) TV
ON TC.CPF = TV.CPF
WHERE TV.MES_ANO = '02-2015';

-------------------- MINHAS QUERIES COM 2 INNER JOINS --------------------------
SELECT TC.NOME,
       TC.VOLUME_DE_COMPRA,
       SUM(INF.QUANTIDADE) VOLUME
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY TC.NOME, TC.VOLUME_DE_COMPRA
ORDER BY TC.NOME;

--Calcular volume vendido por ano de cada cliente
SELECT TO_CHAR(NF.DATA_VENDA,'YYYY'),
       TC.NOME,
       TC.VOLUME_DE_COMPRA AS VOLUME_LIMITE,
       SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA,'YYYY') = 2016
GROUP BY TC.NOME, TC.VOLUME_DE_COMPRA, TO_CHAR(NF.DATA_VENDA,'YYYY')
ORDER BY TC.NOME;

--Calcular volume vendido por mês de cada cliente
SELECT TO_CHAR(NF.DATA_VENDA,'MM-YYYY') AS MES_ANO,   --02-2015
       TC.CPF,   --50534475787
       TC.NOME,  --Abel Silva
       TC.VOLUME_DE_COMPRA AS VOLUME_LIMITE,  --26000
       SUM(INF.QUANTIDADE) AS VOLUME_VENDIDO,  --21325
       (CASE WHEN TC.VOLUME_DE_COMPRA >= SUM(INF.QUANTIDADE) THEN 'VENDAS VÁLIDAS'
       ELSE 'VENDAS INVÁLIDAS' END) AS RESULTADO --VENDAS VÁLIDAS
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA,'MM-YYYY') = '02-2015'
GROUP BY TC.CPF, TC.NOME, TC.VOLUME_DE_COMPRA, TO_CHAR(NF.DATA_VENDA,'MM-YYYY')
ORDER BY TO_CHAR(NF.DATA_VENDA,'MM-YYYY'), TC.NOME;


-- Tirando a prova (teste de mesa)
SELECT TC.NOME, --Abel Silva
       TC.VOLUME_DE_COMPRA AS VOLUME_LIMITE, --26000
       INF.QUANTIDADE AS VOLUME_VENDIDO  --21.325
FROM TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
WHERE TO_CHAR(NF.DATA_VENDA,'MM-YYYY') = '02-2015' 
ORDER BY TC.NOME, VOLUME_VENDIDO;





