--VIEW
--Ela se comporta igual a uma tabela!

-- Peguei da aula de SUBCONSULTA-substituindo-o-HAVING.sql
SELECT SOMA_EMBALAGENS.EMBALAGEM, SOMA_EMBALAGENS.SOMA_PRECO
FROM (
    SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
    FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
    ) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;


CREATE VIEW VW_SOMA_EMBALAGENS AS
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;


SELECT EMBALAGEM, SOMA_PRECO FROM VW_SOMA_EMBALAGENS WHERE SOMA_PRECO >= 0;


--Listar todos os produtos cuja soma das embalagens é maior do que 80
SELECT * FROM TABELA_DE_PRODUTOS TP 
INNER JOIN VW_SOMA_EMBALAGENS VW ON TP.EMBALAGEM = VW.EMBALAGEM
WHERE SOMA_PRECO >= 80;


SELECT * FROM TABELA_DE_PRODUTOS;


SELECT * FROM TABELA_DE_PRODUTOS TP 
INNER JOIN VW_SOMA_EMBALAGENS VW ON TP.EMBALAGEM = VW.EMBALAGEM
--WHERE SOMA_PRECO >= 80
ORDER BY TP.EMBALAGEM DESC, TP.NOME_DO_PRODUTO;